version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpw
      POSTGRES_DB: basetalk
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: kys010306@sogang.ac.kr
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "5050:5050"
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:
