version: "3.8"

services:
  basetalk-crawler:
    image: kys010306/mat4331-basetalk-crawler:latest
    container_name: basetalk-crawler
    ports:
      - "8079:8079"
    env_file:
      - .env
    restart: unless-stopped
