name: Build and Deploy Basetalk Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - project: mat4331-basetalk-ai
            path: mat4331-basetalk-ai/
            hosts:
              - AI_HOST
          - project: mat4331-basetalk-backend
            path: mat4331-basetalk-backend/
            hosts:
              - MAIN_HOST_1
              - MAIN_HOST_2
          - project: mat4331-basetalk-crawler
            path: mat4331-basetalk-crawler/
            host: CRAWLER_HOST

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add SSH Key and Register Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SECRET_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

        shell: bash

      - name: Deploy Service to EC2 instances via Bastion
        run: |
          HOSTS="${{ join(matrix.hosts, ' ') }}"
          for HOST in $HOSTS; do
            ssh -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no" -o "ProxyJump ubuntu@${{ secrets.BASTION_HOST }}" ubuntu@${{ secrets[HOST] }} "
              sudo docker-compose ps -a &&
              echo "hello"
            "
          done
        shell: bash

      - name: Clean up SSH key
        run: |
          rm -f ~/.ssh/id_rsa
        shell: bash
