name: Build and Deploy Basetalk Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - project: mat4331-basetalk-ai
            path: mat4331-basetalk-ai/
          - project: mat4331-basetalk-backend
            path: mat4331-basetalk-backend/
          - project: mat4331-basetalk-crawler
            path: mat4331-basetalk-crawler/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add SSH Key and Register Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SECRET_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

        shell: bash

      - name: Deploy Service to EC2 instances via Bastion
        env:
          BASTION_HOST: ${{ secrets.BASTION_HOST }}
          AI_HOST: ${{ secrets.AI_HOST }}
          MAIN_HOST_1: ${{ secrets.MAIN_HOST_1 }}
          MAIN_HOST_2: ${{ secrets.MAIN_HOST_2 }}
          CRAWLER_HOST: ${{ secrets.CRAWLER_HOST }}
        run: |
          # Determine hosts based on the project
          if [ "${{ matrix.project }}" == "mat4331-basetalk-ai" ]; then
            HOSTS="$AI_HOST"
          elif [ "${{ matrix.project }}" == "mat4331-basetalk-backend" ]; then
            HOSTS="$MAIN_HOST_1 $MAIN_HOST_2"
          elif [ "${{ matrix.project }}" == "mat4331-basetalk-crawler" ]; then
            HOSTS="$CRAWLER_HOST"
          else
            echo "Unknown project: ${{ matrix.project }}"
            exit 1
          fi

          # Deploy to each host
          for HOST in $HOSTS; do
            ssh -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no" -o "ProxyJump ubuntu@$BASTION_HOST" ubuntu@$HOST "
              sudo timedatectl set-timezone Asia/Seoul &&
              sudo docker-compose ps -a &&
              echo "hello"
            "
          done
        shell: bash

      - name: Clean up SSH key
        run: |
          rm -f ~/.ssh/id_rsa
        shell: bash
