name: Build and Deploy Basetalk Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - mat4331-basetalk-ai
          - mat4331-basetalk-backend
          - mat4331-basetalk-crawler

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg BASE_URL="${{ secrets.BASE_URL }}" \
            --build-arg CLIENT_DOMAIN="${{ secrets.CLIENT_DOMAIN }}" \
            --build-arg GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            --build-arg GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            --build-arg JWT_ACCESS_SECRET="${{ secrets.JWT_ACCESS_SECRET }}" \
            --build-arg JWT_REFRESH_SECRET="${{ secrets.JWT_REFRESH_SECRET }}" \
            --build-arg JWT_GRANT_SECRET="${{ secrets.JWT_GRANT_SECRET }}" \
            --build-arg MONGO_DB_URI="${{ secrets.MONGO_DB_URI }}" \
            --build-arg POSTGRES_DATABASE="${{ secrets.POSTGRES_DATABASE }}" \
            --build-arg POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}" \
            --build-arg POSTGRES_USERNAME="${{ secrets.POSTGRES_USERNAME }}" \
            --build-arg POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
            --build-arg RABBITMQ_HOST="${{ secrets.RABBITMQ_HOST }}" \
            --build-arg RABBITMQ_USER="${{ secrets.RABBITMQ_USER }}" \
            --build-arg RABBITMQ_PASSWORD="${{ secrets.RABBITMQ_PASSWORD }}" \
            --build-arg RABBITMQ_URL="${{ secrets.RABBITMQ_URL }}" \
            --build-arg REDIS_HOST="${{ secrets.REDIS_HOST }}" \
            -t kys010306/${{ matrix.project }} ${{ matrix.project }}

      - name: Push Docker Image to DockerHub
        run: |
          docker push kys010306/${{ matrix.project }}
